const { urlCacheKeyWithQuery, urlCacheKeyPHG } = require('./lib');

/**
 * Returns the org id for the current environment
 *
 * @param  {string} staging
 * @param  {string} production
 * @return {string}
 */
function idForEnv(staging, production) {
  return process.env.NODE_ENV === 'production' ? production : staging;
}

// prettier-ignore
const ORGANIZATION_IDS = {
  aaptiv: idForEnv('org-5857b1e8d8335693', 'org-3208ad66bbc20745'),
  abercrombie: idForEnv('org-262d6eae90030df9', 'org-31ff57a596eb49f0'),
  academysports: idForEnv('org-6f7f645283847657', 'org-3a16739777ce659c'),
  aclens: idForEnv('org-2a756cc7fe421416', 'org-2faa3e62d8f0f4c7'),
  advanceautoparts: idForEnv('org-77cd55d02f3aa0fa', 'org-66ba5fac108d982a'),
  adidas: idForEnv('org-573265729ae39579', 'org-20b58763dc73a0e9'),
  ajmadison: idForEnv('org-71540342c104824d', 'org-43574a137b2a7057'),
  aliexpress: idForEnv('org-5abd8cced72bcf03', 'org-496018b77cfa24d2'),
  amazon: idForEnv('org-3b6a623e75cc729c', 'org-237c40fe8ff17a79'),
  americaneagleoutfitters: idForEnv('org-2e053676e576a192', 'org-169368ab844e1195'),
  anntaylor: idForEnv('org-507e4d85331df930', 'org-162d3ce006d3730b'),
  anntaylorfactory: idForEnv('org-08eeb5b95eb0a3a9', 'org-5aa25a953f24687b'),
  applemusic: idForEnv('org-7e4081c0d88c5427', 'org-11a5ee63b284a602'),
  applelite: idForEnv('org-63b88d00c5c45c1c', 'org-0f780698890aab70'),
  asos: idForEnv('org-3a546af44d7a007f', 'org-7bf7cc04876c0896'),
  ashford: idForEnv('org-617e5580a89348e2', 'org-5918a6ce026e72e5'),
  ashleystewart: idForEnv('org-7640a272ebc2de9c', 'org-423a599910b2dd4b'),
  athleta: idForEnv('org-1672b500bb67fc46', 'org-79ec56e9036f5657'),
  atom: idForEnv('org-6c6c57762afd0d79', 'org-593afe99f67b1621'),
  backcountry: idForEnv('org-3bec3b5c0cac44ad', 'org-14b04cbc05ea9632'),
  bananarepublic: idForEnv('org-629421a116a51a7f', 'org-44ae4a864e9b9d35'),
  bananarepublicfactory: idForEnv('org-1d44abf24b56c2ed', 'org-72c9ece58354c89d'),
  bareminerals: idForEnv('org-4ee27094fdc44161', 'org-59a23eadae467372'),
  barenecessities: idForEnv('org-64e721fae05aad0d', 'org-7e294b72146de20b'),
  barkbox: idForEnv('org-6eada664b6b9c1ea', 'org-2032542c337350ce'),
  barnesandnoble: idForEnv('org-61357fd0539adab1', 'org-7aa1b253ee576866'),
  barneys: idForEnv('org-479a3251aed35628', 'org-164a6ec17278f215'),
  barneyswarehouse: idForEnv('org-6bcaec1ad9d8de3d', 'org-77e30018f10eda78'),
  bassproshops: idForEnv('org-4ea814d87bcfe057', 'org-174ffc90f39c31b8'),
  bcbg: idForEnv('org-508eb7aaf7c451a7', 'org-61692ff7cb8a5376'),
  bedbathandbeyond: idForEnv('org-1f3d84fcd15a656b', 'org-73175357d0c91088'),
  belk: idForEnv('org-0d83efbee5076fc4', 'org-6918176300ddc5bd'),
  berries: idForEnv('org-3f37670cdbf299b3', 'org-60fc33a0d28a687c'),
  bestbuy: idForEnv('org-2a425db995f4b810', 'org-5cb8345a370687eb'),
  bestwestern: idForEnv('org-3ed715bfa3e609fa', 'org-65da23ceb1cf2dd2'),
  biglots: idForEnv('org-6c2d7c1c6937062e', 'org-75c78625d80c4956'),
  birchboxuk: idForEnv('org-7008040016c309e8', 'org-701439f2d721a3ec'),
  bloomandwild: idForEnv('org-2705011eae8616ea', 'org-24c5c0bd6859aafb'),
  bloomingdales: idForEnv('org-3bf2420ba71a7180', 'org-1f14e042761984b9'),
  bloomthat: idForEnv('org-717bc2bbb268c3f6', 'org-57714903a5beae6a'),
  blueapron: idForEnv('org-54084c2a9ed41a32', 'org-4e1e36560bea827f'),
  boohoo: idForEnv('org-377e7257e2f67ae8', 'org-4b8f4074acdd6a1d'),
  boohooman: idForEnv('org-356d405580881557', 'org-484ae0f18eb065e7'),
  booking: idForEnv('org-4d6aaae0d30aaa7d', 'org-68bad64fbe9a7fab'),
  boxed: idForEnv('org-372a59a7b6ddb53b', 'org-1fe24b86920e754b'),
  buybuybaby: idForEnv('org-3025275476768a46', 'org-7621ac613f43ceaa'),
  cabelas: idForEnv('org-19090e0a7a9430f6', 'org-2ec030caa66324a1'),
  carhartt: idForEnv('org-68143cdb614ed8eb', 'org-40340ca5bda9ba63'),
  casper: idForEnv('org-1baf990739ef9149', 'org-10f0420c3bc5f6cb'),
  catherines: idForEnv('org-33705c1d475877d5', 'org-5e4e92d8088ce5d7'),
  caviar: idForEnv('org-4bbe43f218248059', 'org-01d3f23da8897379'),
  centurytwentyone: idForEnv('org-64202147c39e86cf', 'org-4a260c81c447c6ef'),
  champion: idForEnv('org-3aa400a4ddb52386', 'org-35acd09f1f45171e'),
  champs: idForEnv('org-536aa54203c3aea1', 'org-0e5041559a708350'),
  charlotterusse: idForEnv('org-6e0a8468eea92342', 'org-0ae78a0118d5b513'),
  cheapoair: idForEnv('org-39fc5b25a4debc2e', 'org-293b06d2e5ceef0d'),
  childrensplace: idForEnv('org-657632e7ef4bd0c5', 'org-19633f94ba588f4e'),
  choicehotels: idForEnv('org-1ca31081509a6894', 'org-7f70aeecd7a3bddb'),
  classpass: idForEnv('org-118610b4b68e691e', 'org-33560fcb0b67d954'),
  cratejoy: idForEnv('org-0bb1927e6f738505', 'org-6dbc9af49ef93d99'),
  clarks: idForEnv('org-19d71226709fe3c0', 'org-42fe4d75497df756'),
  coach: idForEnv('org-621b449613ed8b40', 'org-236a9999b9362e3c'),
  costplusworldmarket: idForEnv('org-7c42436567440f84', 'org-3a52110b275c7315'),
  cvs: idForEnv('org-029e10645f2dde49', 'org-4f800dd20193bb1e'),
  deliverydotcom: idForEnv('org-0c9334a8b3947ccc', 'org-1dc9285481600e52'),
  dickssportinggoods: idForEnv('org-0332550eb8b15f4d', 'org-7231d7ace317c483'),
  dockers: idForEnv('org-35646980f9b3169d', 'org-4d103c612492caa3'),
  dollar: idForEnv('org-22e9e461320816cb', 'org-591576541710f05c'),
  doordash: idForEnv('org-11fd3065b9c49c90', 'org-358eb2fe857a41c0'),
  drizly: idForEnv('org-1d159507be3d049e', 'org-6b5289aed25f6390'),
  ebags: idForEnv('org-67cb320e6548dfb3', 'org-370ffc644a4db75f'),
  ebay: idForEnv('org-5d63b849c1d24db2', 'org-6bef1aa726081cf9'),
  eddiebauer: idForEnv('org-6ace1d44dd626012', 'org-00fa1dd4d5187c91'),
  eileenfisher: idForEnv('org-56b5669b828c346d', 'org-2a4fb0b97d5cbd32'),
  eloquii: idForEnv('org-063ada4cde3b4530', 'org-0224b5d53929da26'),
  enterprise: idForEnv('org-299546bbc4e4986b', 'org-4e63bffcdd3ec5c2'),
  etsy: idForEnv('org-3ee55c6f49b96819', 'org-2d6541eb62090c79'),
  expedia: idForEnv('org-404d3602c71bd428', 'org-213f3e4d239a7920'),
  express: idForEnv('org-3acb6dc42678c843', 'org-1f8bb66ff44ca946'),
  extendedstayamerica: idForEnv('org-66699b7f8d07d73a', 'org-2dedd9d0fe73e21e'),
  famousfootwear: idForEnv('org-44faa5b122bafdbe', 'org-04ddb4f5675f8916'),
  fandango: idForEnv('org-335da7cf480ee9ec', 'org-0f7d89295b6c0203'),
  firstchoice: idForEnv('org-48b4ca374f986a23', 'org-2c8e257e691a9237'),
  footlocker: idForEnv('org-4a65238ed2811743', 'org-0a704e68d9157af0'),
  forevertwentyone: idForEnv('org-4c453fc80d75912d', 'org-3e08edd1defc0bb4'),
  ftd: idForEnv('org-2de7a469d485ee49', 'org-70b72ebe26276654'),
  game: idForEnv('org-41c74011dc2eec5a', 'org-396d9d1c6cbaa597'),
  gamestop: idForEnv('org-139f1edad7388c6a', 'org-0c642216a15a1f95'),
  gap: idForEnv('org-319e4a77607c0ae6', 'org-10056a6c4b9f45da'),
  gapfactory: idForEnv('org-03dc917e26ebbc32', 'org-359c5d2e16964fd5'),
  glossybox: idForEnv('org-25740638c0bcbc4b', 'org-7789fce2df3c5f7a'),
  gnc: idForEnv('org-17129f7d0968289c', 'org-6624191d499647f2'),
  goodyear: idForEnv('org-5b2a539455f3adb9', 'org-2759be989dbaf706'),
  greenchef: idForEnv('org-39b67fac48cabdc8', 'org-04a62be62aca7a6b'),
  groupon: idForEnv('org-681847bf6cc4d57c', 'org-46cb47cf8637e3d6'),
  grubhub: idForEnv('org-1cd5b143f9e24cba', 'org-52384c00733c60c5'),
  gymshark: idForEnv('org-306d5b9fb5eb256a', 'org-79ca35cb8ff4c50f'),
  buttonia: idForEnv('org-34078c4621166ed0', 'org-505e034605a6741f'),
  hanes: idForEnv('org-19db578ff508b3d6', 'org-2bcf6eb859912e70'),
  happysocks: idForEnv('org-45182374654dc7f3', 'org-3f8b301f55b0c151'),
  hellofresh: idForEnv('org-30c1301231586c3a', 'org-0c1a4a9bdd28984b'),
  hertz: idForEnv('org-19b6ce0d40f24fe9', 'org-2de67cefe5c640d6'),
  hollar: idForEnv('org-6c44299ea17a4656', 'org-6aa99f0dcab1dee1'),
  hollister: idForEnv('org-55958981cbd6a05e', 'org-5517f820141d30a9'),
  homeaway: idForEnv('org-64c93a051955f740', 'org-4540d45c863f8d8e'),
  homechef: idForEnv('org-7db8159f970be649', 'org-525633e8b040536e'),
  homedepot: idForEnv('org-68c46e2d9aec87e7', 'org-224cb852ef9c94f7'),
  hotelsdotcom: idForEnv('org-3573c6b896624279', 'org-3a4aad7eb3f326d0'),
  hotelstorm: idForEnv('org-047a60621cef0d87', 'org-722450a0945f2eb6'),
  hoteltonight: idForEnv('org-36fe49ce9ccb9116', 'org-2a63ae96742c3e1c'),
  hotwire: idForEnv('org-7829938c0c640b81', 'org-7b991de7f1a97f15'),
  houzz: idForEnv('org-03418dec42db44bc', 'org-1b931f59516ac887'),
  hp: idForEnv('org-6bd3d6a70b2043a5', 'org-41f6254ceb763673'),
  hrblock: idForEnv('org-2be6d27b8b94404c', 'org-3758ea2ed006658e'),
  hsn: idForEnv('org-47dd49da0eec165a', 'org-358f3f272215d6ae'),
  hulu: idForEnv('org-0b5f98435860b9c5', 'org-58e9067c3af2717f'),
  hurley: idForEnv('org-6d43cd2a602bb412', 'org-5052f8a2e1ceed80'),
  instacart: idForEnv('org-1b9289f2f9014476', 'org-21a5a7ea2f27bf2f'),
  hungryhouse: idForEnv('org-714d6d52c2e268ac', 'org-3c557a8ba21a64a5'),
  ihg: idForEnv('org-51bf213e0efdd052', 'org-4864bd8faa4a45df'),
  itunes: idForEnv('org-08ddcdc47b8479f9', 'org-16e46a4f99ffb60e'),
  jcpenney: idForEnv('org-2f11b9727eac5e8b', 'org-7871459c5577c899'),
  jcrew: idForEnv('org-0cc5dd183cb33758', 'org-575cd4068e21a8ce'),
  jet: idForEnv('org-7edde2ff2a553edd', 'org-01e12b03f6a07d54'),
  jimmyjazz: idForEnv('org-4d8a1762a729f3f7', 'org-2191524d25ff9fe3'),
  joann: idForEnv('org-67a62f95dcf52263', 'org-47bf2bcf5a868be0'),
  journeys: idForEnv('org-50aae70809ac3274', 'org-1ed4cc58321f4d17'),
  kohls: idForEnv('org-2ef55bcceba936bf', 'org-6084c79ded3b361d'),
  lanebryant: idForEnv('org-1aacc5590d521349', 'org-0dd00806d3213c5f'),
  levi: idForEnv('org-254cb0fb6da55b06', 'org-19510c8daf9627f4'),
  livingsocial: idForEnv('org-3245bc46bdfbde74', 'org-7021ca2bba342684'),
  loccitane: idForEnv('org-30397e1f6f772bd4', 'org-6031843aa4b0af8f'),
  loewshotels: idForEnv('org-18731bdd4a79263e', 'org-2b91eb357bbf2fce'),
  loft: idForEnv('org-0b593e51803c750d', 'org-6dad864932b6710f'),
  loftoutlet: idForEnv('org-2bea0747eab6b7e4', 'org-732d8246ae13d753'),
  lookfantastic: idForEnv('org-43d3b3af2c665845', 'org-531e10d4cca3105c'),
  lordandtaylor: idForEnv('org-0f116a831b9b74ce', 'org-2c5df3adaf2bf9a6'),
  lowes: idForEnv('org-49c44db5c0f88c9f', 'org-4e025d1bc42d3dfc'),
  luckybrand: idForEnv('org-4646befd71510d10', 'org-0e75522407c5bc00'),
  lyft: idForEnv('org-5ee4b6c77217fd5f', 'org-6ea7e006d4747da5'),
  macys: idForEnv('org-7bfb8e7a4771a0f6', 'org-49cb6ac206ad80ef'),
  matchuk: idForEnv('org-2db5c92a9521e212', 'org-7eb8012755df9f1a'),
  maurices: idForEnv('org-654c89095f9023eb', 'org-2febb032ab0b051c'),
  menswearhouse: idForEnv('org-349d5283e55573dc', 'org-2707d289a17de31a'),
  minibar: idForEnv('org-6539d5fcc80478f9', 'org-454e774784026cf3'),
  modcloth: idForEnv('org-382484c03d49c2e7', 'org-1273d3ec67e34bc8'),
  moosejaw: idForEnv('org-4f3cf7df6b40fac3', 'org-353705da535d883f'),
  mrandmrssmith: idForEnv('org-4a2d4ae6a222295d', 'org-3acd26a72302ef1d'),
  murad: idForEnv('org-7dc6406e04c053aa', 'org-087cce8ecbdcead8'),
  mvmt: idForEnv('org-22e0c0464157d00d', 'org-049041ef803b7bff'),
  mymms: idForEnv('org-6ca394e5f6fe8cef', 'org-1849dbf2940556cb'),
  neimanmarcus: idForEnv('org-6ed12197d645cb96', 'org-2aaa7f792e1fd2a4'),
  newbalance: idForEnv('org-6d7da004ff5cdcf1', 'org-2820176af1c38fd4'),
  newegg: idForEnv('org-7551589b380cb00d', 'org-122ac7228f689951'),
  nike: idForEnv('org-489937a7411317d5', 'org-114d74719e0b55b5'),
  nordstrom: idForEnv('org-2f2a3205412f1d16', 'org-26d699e4f5d381a7'),
  nyandcompany: idForEnv('org-5287c897e86dc2c7', 'org-060e1ea199b431a6'),
  officedepot: idForEnv('org-38d6299f9b9ac534', 'org-6a9489141bf51b99'),
  oldnavy: idForEnv('org-430deef57127f23a', 'org-5d09ca3215ac4f8b'),
  oneeighthundredcontacts: idForEnv('org-26682ada31a5a969', 'org-559d44169f9644b2'),
  oneeighthundredflowers: idForEnv('org-78f56ab485a9d61e', 'org-2262ebf39b452f55'),
  opentable: idForEnv('org-1381881532ffe9f4', 'org-152a3da601ea842e'),
  orbitz: idForEnv('org-4a0bc241035d5004', 'org-40e671b4821bba85'),
  overstock: idForEnv('org-695642d20753707a', 'org-61f91580f4ee7bd8'),
  payless: idForEnv('org-701cf78cf127d8bb', 'org-484b829c85cb7afa'),
  perfumania: idForEnv('org-6cbd66946eb9521d', 'org-4d857696cdefed1b'),
  petcaresupplies: idForEnv('org-222749ef79541229', 'org-14fca63f1e8f5639'),
  petco: idForEnv('org-37286d1fe134497a', 'org-0ac1f4d67d609a28'),
  petsmart: idForEnv('org-737feefaa4027acd', 'org-7fe1284e246156af'),
  photobox: idForEnv('org-3bbe852185daa017', 'org-3bfa4cc9c4d036d7'),
  pieroneimports: idForEnv('org-1dde8d4ff9bf600b', 'org-47313a073be635ef'),
  poshmark: idForEnv('org-59593cbf9713a5fc', 'org-131504b5b7b2bd8f'),
  priceline: idForEnv('org-3d58ee483aaab250', 'org-647800d57126630c'),
  priverevaux: idForEnv('org-0af52805eb6c388b', 'org-78774db76dbfd474'),
  proflowers: idForEnv('org-3aa02f2615052e9b', 'org-15b4536b915f6936'),
  puritanspride: idForEnv('org-03a884850802a1cb', 'org-5530daa5f15dd613'),
  quandoo: idForEnv('org-6b6a1003c3e5161f', 'org-087998189f5d94a3'),
  qvc: idForEnv('org-48b55e692be2e29e', 'org-60b61bf43617aa3a'),
  resy: idForEnv('org-273ae234ce730ab5', 'org-5bc8df951b113f0b'),
  rentalcarsdotcom: idForEnv('org-4b79520b0ebcc89b', 'org-748ba1f8cfd0a523'),
  rover: idForEnv('org-5d21dee9ec7165a7', 'org-5cebfdeeb8931e75'),
  safeway: idForEnv('org-493cb268b72df875', 'org-43da2e9700370062'),
  saks: idForEnv('org-467d5b2e0fa71865', 'org-6a9507ab7de82b0f'),
  saksfifthavenue: idForEnv('org-141dc1b66b1dadd7', 'org-1a784c14cfd29642'),
  samsclub: idForEnv('org-038ecf7c962b91d1', 'org-47583f87f3e1331f'),
  samsungdotcom: idForEnv('org-2adb61dabaacc7cd', 'org-1670fcdc8aef00c3'),
  sears: idForEnv('org-36467c8b060acf5a', 'org-0a83fe21a169704a'),
  seatgeek: idForEnv('org-00eb446216ab549a', 'org-15ca11330e902cdc'),
  sephora: idForEnv('org-5cdc1a582cc682d7', 'org-2eeecdfc5daa839a'),
  shoesdotcom: idForEnv('org-3272edb3586efeb2', 'org-7bc4103bcd1b31e6'),
  shoeline: idForEnv('org-74b289f680ee55c1', 'org-57e0455999fd59da'),
  shopdisney: idForEnv('org-5112e926c9ede39a', 'org-1a1066d59930fff4'),
  shipt: idForEnv('org-2bcee4484d044026', 'org-0515b8a65fb8f97c'),
  sierratradingpost: idForEnv('org-7d358f1fd7cf89c0', 'org-03a4099575ea69eb'),
  siriusxm: idForEnv('org-7c8522218d8e2ab8', 'org-70e74eb4e490a8f9'),
  sixzerotwo: idForEnv('org-5a6700ebe4a4895a', 'org-407d2f08facfa1a1'),
  skinstore: idForEnv('org-52755d07d1200794', 'org-4936584820669a2b'),
  societysix: idForEnv('org-09a55801fb09eba5', 'org-6cb168c00a150922'),
  soma: idForEnv('org-53868df05a5a962b', 'org-04cd3ef0165be794'),
  splendid: idForEnv('org-69e5b82c6aea2750', 'org-29f053216e87680c'),
  stevemadden: idForEnv('org-3f1c7e44c6786515', 'org-5533145e836f8d1d'),
  spring: idForEnv('org-5f8137923a8ee6e3', 'org-1205d831b97b8898'),
  staples: idForEnv('org-119a47243eec5456', 'org-3bf682099acce59b'),
  staplesuk: idForEnv('org-77366066ec3b1302', 'org-4460743536a2805f'),
  stasher: idForEnv('org-39656f81c033a5f8', 'org-4b0332f7f1c01723'),
  stitchfix: idForEnv('org-33fbd5f8fc3214c4', 'org-7f2a65dec2f40c6e'),
  strollerhaus: idForEnv('org-2cd5465b96631f98', 'org-1c85c47d5dc0ba79'),
  superdry: idForEnv('org-149f1835453e9b25', 'org-2a4d3c8e08e42270'),
  target: idForEnv('org-24621b367f4280bc', 'org-2bf249f48f5c19e5'),
  techarmor: idForEnv('org-6ef589c578ab8ac6', 'org-20b982d7d1140972'),
  tedbaker: idForEnv('org-1b6dd43d7491fcca', 'org-7188b485cac95d0f'),
  thebodyshop: idForEnv('org-042ed5be9add21b1', 'org-314afc3876f47d9d'),
  thehonestcompany: idForEnv('org-69f48b3772a0ff50', 'org-6944fb5d855017ea'),
  thelimited: idForEnv('org-17dd3a159e3a594f', 'org-3a05931d511a1e76'),
  thredup: idForEnv('org-3c49e594181aec3a', 'org-6917f00190e56f65'),
  thrifty: idForEnv('org-6f8e0ae8d4b0f28d', 'org-76f47bd526dae215'),
  thrivemarket: idForEnv('org-013e2e3ddf915475', 'org-11f852b9cd45fedd'),
  ticketmaster: idForEnv('org-12442b0c35f7f8bb', 'org-541729bd3e156a58'),
  tillys: idForEnv('org-015a0aab2b818a59', 'org-3919f3c6b66f7aeb'),
  tommy: idForEnv('org-5bc8da8c2376cde8', 'org-024abe623b4d34e1'),
  tophatter: idForEnv('org-799ada74ea8a8b8c', 'org-2ff7f44805bbfcd1'),
  touchofmodern: idForEnv('org-3a963cada429a817', 'org-60e3c621fbf5849a'),
  travelocity: idForEnv('org-09b845f7f5293f1a', 'org-38f81446b1d10ef2'),
  tripadvisor: idForEnv('org-1841455a334240f6', 'org-095e61f87d0b77ea'),
  uber: idForEnv('org-3f6f45d041e575c0', 'org-233e9d9b676a9ad0'),
  uberrewards: idForEnv('org-71d525a52970fe14', 'org-1be0ab0ff68b10be'),
  ulta: idForEnv('org-2777b585ec89b363', 'org-4f12fbdfceadbd4f'),
  underarmour: idForEnv('org-68f62bd9e3c6299d', 'org-4d6fc40af1133350'),
  viator: idForEnv('org-7aae97fa03a97e54', 'org-3c5a6f0c3f0b02bc'),
  vitacost: idForEnv('org-70251c891e2511e7', 'org-2fe99a62e4e627a6'),
  vitaminworld: idForEnv('org-7124d3e9197df177', 'org-3f1ee004c3911b4e'),
  vividseats: idForEnv('org-0bf5185d0e4e8813', 'org-431907f17f782c9f'),
  vrbo: idForEnv('org-356a52da342df057', 'org-38f5de379d196cf1'),
  walgreens: idForEnv('org-20a3f0e8c6c5ae2c', 'org-6929d8a51beb9e62'),
  thewalkingcompany: idForEnv('org-681387e37b68b750', 'org-633c1fe7445a8ad5'),
  walmart: idForEnv('org-2365a4c935cb296b', 'org-106cb4462581719b'),
  warbyparker: idForEnv('org-2fd15d5ed979b077', 'org-72157f113f3ccc79'),
  winedotcom: idForEnv('org-5dd391b9cf84fc26', 'org-5726711398b0f1ad'),
  yoox: idForEnv('org-47d17720c94e455e', 'org-18019d732a7cf04f'),
  zaful: idForEnv('org-2f03d3b932a7efe7', 'org-382ba22e63a6e954'),
  zulily: idForEnv('org-71667af58d3a875e', 'org-07b93b511ac9a4b8'),
  testmerchant: idForEnv('org-02d94d8fe71f12b0', 'org-228b55a5707de5c8'),
};

/**
 * Supported Merchants are the global list of supported merchant hostnames
 * supported by link enhancement/generation.
 *
 * Supported Merchants have the following schema:
 *
 * hostname [string]: The hostname, including subdomains of the merchant
 * organization_id [string]: The Button merchant organization id.
 */
// prettier-ignore
const SUPPORTED_MERCHANTS = [
  { hostname: '1800contacts.com', organization_id: ORGANIZATION_IDS.oneeighthundredcontacts },
  { hostname: '1800flowers.com', organization_id: ORGANIZATION_IDS.oneeighthundredflowers },
  { hostname: 'aaptiv.com', organization_id: ORGANIZATION_IDS.aaptiv },
  { hostname: 'abercrombie.com', organization_id: ORGANIZATION_IDS.abercrombie },
  { hostname: 'aclens.com', organization_id: ORGANIZATION_IDS.aclens },
  { hostname: 'academy.com', organization_id: ORGANIZATION_IDS.academysports },
  { hostname: 'adidas.com', organization_id: ORGANIZATION_IDS.adidas },
  { hostname: 'advanceautoparts.com', organization_id: ORGANIZATION_IDS.advanceautoparts },
  { hostname: 'ajmadison.com', organization_id: ORGANIZATION_IDS.ajmadison },
  { hostname: 'ashleystewart.com', organization_id: ORGANIZATION_IDS.ashleystewart },
  { hostname: 'shop.advanceautoparts.com', organization_id: ORGANIZATION_IDS.advanceautoparts },
  { hostname: 'ae.com', organization_id: ORGANIZATION_IDS.americaneagleoutfitters },
  { hostname: 'aliexpress.com', organization_id: ORGANIZATION_IDS.aliexpress },
  { hostname: 'amazon.com', organization_id: ORGANIZATION_IDS.amazon },
  { hostname: 'anntaylor.com', organization_id: ORGANIZATION_IDS.anntaylor },
  { hostname: 'factory.anntaylor.com', organization_id: ORGANIZATION_IDS.anntaylorfactory },
  { hostname: 'apple.com', organization_id: ORGANIZATION_IDS.applelite },
  { hostname: 'asos.com', organization_id: ORGANIZATION_IDS.asos },
  { hostname: 'asos.de', organization_id: ORGANIZATION_IDS.asos },
  { hostname: 'asos.fr', organization_id: ORGANIZATION_IDS.asos },
  { hostname: 'm.asos.com', organization_id: ORGANIZATION_IDS.asos },
  { hostname: 'au.asos.com', organization_id: ORGANIZATION_IDS.asos },
  { hostname: 'us.asos.com', organization_id: ORGANIZATION_IDS.asos },
  { hostname: 'ashford.com', organization_id: ORGANIZATION_IDS.ashford },
  { hostname: 'athleta.com', organization_id: ORGANIZATION_IDS.athleta },
  { hostname: 'athleta.gap.com', organization_id: ORGANIZATION_IDS.athleta },
  { hostname: 'atomtickets.com', organization_id: ORGANIZATION_IDS.atom },
  { hostname: 'backcountry.com', organization_id: ORGANIZATION_IDS.backcountry },
  { hostname: 'bananarepublic.com', organization_id: ORGANIZATION_IDS.bananarepublic },
  { hostname: 'bananarepublic.gap.com', organization_id: ORGANIZATION_IDS.bananarepublic },
  { hostname: 'bananarepublicfactory.com', organization_id: ORGANIZATION_IDS.bananarepublicfactory },
  { hostname: 'bananarepublicfactory.gapfactory.com', organization_id: ORGANIZATION_IDS.bananarepublicfactory },
  { hostname: 'bareminerals.com', organization_id: ORGANIZATION_IDS.bareminerals },
  { hostname: 'barenecessities.com', organization_id: ORGANIZATION_IDS.barenecessities },
  { hostname: 'barkbox.com', organization_id: ORGANIZATION_IDS.barkbox },
  { hostname: 'barneys.com', organization_id: ORGANIZATION_IDS.barneys },
  { hostname: 'barneyswarehouse.com', organization_id: ORGANIZATION_IDS.barneyswarehouse },
  { hostname: 'barnesandnoble.com', organization_id: ORGANIZATION_IDS.barnesandnoble },
  { hostname: 'basspro.com', organization_id: ORGANIZATION_IDS.bassproshops },
  { hostname: 'bcbg.com', organization_id: ORGANIZATION_IDS.bcbg },
  { hostname: 'bedbathandbeyond.com', organization_id: ORGANIZATION_IDS.bedbathandbeyond },
  { hostname: 'belk.com', organization_id: ORGANIZATION_IDS.belk },
  { hostname: 'berries.com', organization_id: ORGANIZATION_IDS.berries },
  { hostname: 'bestbuy.com', organization_id: ORGANIZATION_IDS.bestbuy },
  { hostname: 'bestwestern.com', organization_id: ORGANIZATION_IDS.bestwestern },
  { hostname: 'biglots.com', organization_id: ORGANIZATION_IDS.biglots },
  { hostname: 'birchbox.co.uk', organization_id: ORGANIZATION_IDS.birchboxuk },
  { hostname: 'bloomandwild.com', organization_id: ORGANIZATION_IDS.bloomandwild },
  { hostname: 'bloomingdales.com', organization_id: ORGANIZATION_IDS.bloomingdales },
  { hostname: 'bloomthat.com', organization_id: ORGANIZATION_IDS.bloomthat },
  { hostname: 'blueapron.com', organization_id: ORGANIZATION_IDS.blueapron },
  { hostname: 'booking.com', organization_id: ORGANIZATION_IDS.booking },
  { hostname: 'boohoo.com', organization_id: ORGANIZATION_IDS.boohoo },
  { hostname: 'boohooman.com', organization_id: ORGANIZATION_IDS.boohooman },
  { hostname: 'boxed.com', organization_id: ORGANIZATION_IDS.boxed },
  { hostname: 'buybuybaby.com', organization_id: ORGANIZATION_IDS.buybuybaby },
  { hostname: 'cabelas.com', organization_id: ORGANIZATION_IDS.cabelas },
  { hostname: 'carhartt.com', organization_id: ORGANIZATION_IDS.carhartt },
  { hostname: 'casper.com', organization_id: ORGANIZATION_IDS.casper },
  { hostname: 'catherines.com', organization_id: ORGANIZATION_IDS.catherines },
  { hostname: 'century21.com', organization_id: ORGANIZATION_IDS.centurytwentyone },
  { hostname: 'champion.com', organization_id: ORGANIZATION_IDS.champion },
  { hostname: 'champssports.com', organization_id: ORGANIZATION_IDS.champs },
  { hostname: 'm.champssports.com', organization_id: ORGANIZATION_IDS.champs },
  { hostname: 'charlotterusse.com', organization_id: ORGANIZATION_IDS.charlotterusse },
  { hostname: 'cheapoair.com', organization_id: ORGANIZATION_IDS.cheapoair },
  { hostname: 'childrensplace.com', organization_id: ORGANIZATION_IDS.childrensplace },
  { hostname: 'choicehotels.com', organization_id: ORGANIZATION_IDS.choicehotels },
  { hostname: 'clarks.com', organization_id: ORGANIZATION_IDS.clarks },
  { hostname: 'clarksusa.com', organization_id: ORGANIZATION_IDS.clarks },
  { hostname: 'classpass.com', organization_id: ORGANIZATION_IDS.classpass },
  { hostname: 'coach.com', organization_id: ORGANIZATION_IDS.coach },
  { hostname: 'cratejoy.com', organization_id: ORGANIZATION_IDS.cratejoy },
  { hostname: 'cvs.com', organization_id: ORGANIZATION_IDS.cvs },
  { hostname: 'delivery.com', organization_id: ORGANIZATION_IDS.deliverydotcom },
  { hostname: 'dickssportinggoods.com', organization_id: ORGANIZATION_IDS.dickssportinggoods },
  { hostname: 'dollar.com', organization_id: ORGANIZATION_IDS.dollar },
  { hostname: 'dockers.com', organization_id: ORGANIZATION_IDS.dockers },
  { hostname: 'doordash.com', organization_id: ORGANIZATION_IDS.doordash },
  { hostname: 'drizly.com', organization_id: ORGANIZATION_IDS.drizly },
  { hostname: 'ebags.com', organization_id: ORGANIZATION_IDS.ebags },
  { hostname: 'ebay.at', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.be', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.ca', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.ch', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.co.uk', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.com', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.com.au', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.de', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.es', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.fr', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.ie', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.it', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'ebay.nl', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.at', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.be', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.ca', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.ch', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.co.uk', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.com', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.com.au', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.de', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.es', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.fr', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.ie', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.it', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'm.ebay.nl', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'eddiebauer.com', organization_id: ORGANIZATION_IDS.eddiebauer },
  { hostname: 'eileenfisher.com', organization_id: ORGANIZATION_IDS.eileenfisher },
  { hostname: 'eloquii.com', organization_id: ORGANIZATION_IDS.eloquii },
  { hostname: 'enterprise.com', organization_id: ORGANIZATION_IDS.enterprise },
  { hostname: 'etsy.com', organization_id: ORGANIZATION_IDS.etsy },
  { hostname: 'etsy.ca', organization_id: ORGANIZATION_IDS.etsy },
  { hostname: 'expedia.com.au', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.de', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.es', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.fr', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.co.id', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.com.my', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.com.ph', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.com.sg', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.co.th', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.com.tw', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.co.uk', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'expedia.com', organization_id: ORGANIZATION_IDS.expedia },
  { hostname: 'express.com', organization_id: ORGANIZATION_IDS.express },
  { hostname: 'extendedstayamerica.com', organization_id: ORGANIZATION_IDS.extendedstayamerica },
  { hostname: 'famousfootwear.com', organization_id: ORGANIZATION_IDS.famousfootwear },
  { hostname: 'fandango.com', organization_id: ORGANIZATION_IDS.fandango },
  { hostname: 'firstchoice.co.uk', organization_id: ORGANIZATION_IDS.firstchoice },
  { hostname: 'footlocker.com', organization_id: ORGANIZATION_IDS.footlocker },
  { hostname: 'forever21.com', organization_id: ORGANIZATION_IDS.forevertwentyone },
  { hostname: 'ftd.com', organization_id: ORGANIZATION_IDS.ftd },
  { hostname: 'game.co.uk', organization_id: ORGANIZATION_IDS.game },
  { hostname: 'gamestop.com', organization_id: ORGANIZATION_IDS.gamestop },
  { hostname: 'gap.com', organization_id: ORGANIZATION_IDS.gap },
  { hostname: 'gapfactory.com', organization_id: ORGANIZATION_IDS.gapfactory },
  { hostname: 'gnc.com', organization_id: ORGANIZATION_IDS.gnc },
  { hostname: 'glossybox.com', organization_id: ORGANIZATION_IDS.glossybox },
  { hostname: 'goodyear.com', organization_id: ORGANIZATION_IDS.goodyear },
  { hostname: 'greenchef.com', organization_id: ORGANIZATION_IDS.greenchef },
  { hostname: 'groupon.ae', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.com.au', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.be', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.de', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.es', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.fr', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.ie', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.it', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.nl', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'grouponnz.co.nz', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.pl', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.co.uk', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'groupon.com', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.ae', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.be', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.co.uk', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.com.au', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.de', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.es', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.fr', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.ie', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.it', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.nl', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.groupon.pl', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 't.grouponnz.co.nz', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'tracking.groupon.com', organization_id: ORGANIZATION_IDS.groupon },
  { hostname: 'grubhub.com', organization_id: ORGANIZATION_IDS.grubhub },
  { hostname: 'gymshark.com', organization_id: ORGANIZATION_IDS.gymshark },
  { hostname: 'buttonia.co', organization_id: ORGANIZATION_IDS.buttonia },
  { hostname: 'hanes.com', organization_id: ORGANIZATION_IDS.hanes },
  { hostname: 'happysocks.com', organization_id: ORGANIZATION_IDS.happysocks },
  { hostname: 'hellofresh.com', organization_id: ORGANIZATION_IDS.hellofresh },
  { hostname: 'hertz.com', organization_id: ORGANIZATION_IDS.hertz },
  { hostname: 'hollisterco.com', organization_id: ORGANIZATION_IDS.hollister },
  { hostname: 'hollar.com', organization_id: ORGANIZATION_IDS.hollar },
  { hostname: 'homeaway.com', organization_id: ORGANIZATION_IDS.homeaway },
  { hostname: 'homechef.com', organization_id: ORGANIZATION_IDS.homechef },
  { hostname: 'homedepot.com', organization_id: ORGANIZATION_IDS.homedepot },
  { hostname: 'honest.com', organization_id: ORGANIZATION_IDS.thehonestcompany },
  { hostname: 'hsn.com', organization_id: ORGANIZATION_IDS.hsn },
  { hostname: 'hoteis.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'au.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'ca.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'ch.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'de.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'es.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'fi.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'fr.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'ie.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'it.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'sg.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'sv.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'uk.hotels.com', organization_id: ORGANIZATION_IDS.hotelsdotcom },
  { hostname: 'hotelstorm.com', organization_id: ORGANIZATION_IDS.hotelstorm },
  { hostname: 'hoteltonight.com', organization_id: ORGANIZATION_IDS.hoteltonight },
  { hostname: 'hotwire.com', organization_id: ORGANIZATION_IDS.hotwire },
  { hostname: 'houzz.com', organization_id: ORGANIZATION_IDS.houzz },
  { hostname: 'houzz.co.uk', organization_id: ORGANIZATION_IDS.houzz },
  { hostname: 'hp.com', organization_id: ORGANIZATION_IDS.hp },
  { hostname: 'store.hp.com', organization_id: ORGANIZATION_IDS.hp },
  { hostname: 'hrblock.com', organization_id: ORGANIZATION_IDS.hrblock },
  { hostname: 'hulu.com', organization_id: ORGANIZATION_IDS.hulu },
  { hostname: 'hungryhouse.co.uk', organization_id: ORGANIZATION_IDS.hungryhouse },
  { hostname: 'hurley.com', organization_id: ORGANIZATION_IDS.hurley },
  { hostname: 'ihg.com', organization_id: ORGANIZATION_IDS.ihg },
  { hostname: 'instacart.com', organization_id: ORGANIZATION_IDS.instacart },
  { hostname: 'itunes.apple.com', organization_id: ORGANIZATION_IDS.applemusic },
  { hostname: 'itunes.apple.com', query_regex: String.raw`(?:^|&)app=itunes(?:&|$)`, organization_id: ORGANIZATION_IDS.itunes },
  { hostname: 'jcpenney.com', organization_id: ORGANIZATION_IDS.jcpenney },
  { hostname: 'm.jcpenney.com', organization_id: ORGANIZATION_IDS.jcpenney },
  { hostname: 'jcrew.com', organization_id: ORGANIZATION_IDS.jcrew },
  { hostname: 'jet.com', organization_id: ORGANIZATION_IDS.jet },
  { hostname: 'jimmyjazz.com', organization_id: ORGANIZATION_IDS.jimmyjazz },
  { hostname: 'joann.com', organization_id: ORGANIZATION_IDS.joann },
  { hostname: 'journeys.com', organization_id: ORGANIZATION_IDS.journeys },
  { hostname: 'kohls.com', organization_id: ORGANIZATION_IDS.kohls },
  { hostname: 'lanebryant.com', organization_id: ORGANIZATION_IDS.lanebryant },
  { hostname: 'levi.com', organization_id: ORGANIZATION_IDS.levi },
  { hostname: 'livingsocial.com', organization_id: ORGANIZATION_IDS.livingsocial },
  { hostname: 'loccitane.com', organization_id: ORGANIZATION_IDS.loccitane },
  { hostname: 'usa.loccitane.com', organization_id: ORGANIZATION_IDS.loccitane },
  { hostname: 'loft.com', organization_id: ORGANIZATION_IDS.loft },
  { hostname: 'outlet.loft.com', organization_id: ORGANIZATION_IDS.loftoutlet },
  { hostname: 'lordandtaylor.com', organization_id: ORGANIZATION_IDS.lordandtaylor },
  { hostname: 'loewshotels.com', organization_id: ORGANIZATION_IDS.loewshotels },
  { hostname: 'lookfantastic.com', organization_id: ORGANIZATION_IDS.lookfantastic },
  { hostname: 'us.lookfantastic.com', organization_id: ORGANIZATION_IDS.lookfantastic },
  { hostname: 'lowes.com', organization_id: ORGANIZATION_IDS.lowes },
  { hostname: 'luckybrand.com', organization_id: ORGANIZATION_IDS.luckybrand },
  { hostname: 'lyft.com', organization_id: ORGANIZATION_IDS.lyft },
  { hostname: 'macys.com', organization_id: ORGANIZATION_IDS.macys },
  { hostname: 'm.macys.com', organization_id: ORGANIZATION_IDS.macys },
  { hostname: 'maurices.com', organization_id: ORGANIZATION_IDS.maurices },
  { hostname: 'uk.match.com', organization_id: ORGANIZATION_IDS.matchuk },
  { hostname: 'menswearhouse.com', organization_id: ORGANIZATION_IDS.menswearhouse },
  { hostname: 'minibardelivery.com', organization_id: ORGANIZATION_IDS.minibar },
  { hostname: 'modcloth.com', organization_id: ORGANIZATION_IDS.modcloth },
  { hostname: 'moosejaw.com', organization_id: ORGANIZATION_IDS.moosejaw },
  { hostname: 'mrandmrssmith.com', organization_id: ORGANIZATION_IDS.mrandmrssmith },
  { hostname: 'murad.com', organization_id: ORGANIZATION_IDS.murad },
  { hostname: 'mvmtwatches.com', organization_id: ORGANIZATION_IDS.mvmt },
  { hostname: 'mymms.com', organization_id: ORGANIZATION_IDS.mymms },
  { hostname: 'neimanmarcus.com', organization_id: ORGANIZATION_IDS.neimanmarcus },
  { hostname: 'newbalance.com', organization_id: ORGANIZATION_IDS.newbalance },
  { hostname: 'newegg.com', organization_id: ORGANIZATION_IDS.newegg },
  { hostname: 'nike.com', organization_id: ORGANIZATION_IDS.nike },
  { hostname: 'nordstrom.com', organization_id: ORGANIZATION_IDS.nordstrom },
  { hostname: 'shop.nordstrom.com', organization_id: ORGANIZATION_IDS.nordstrom },
  { hostname: 'nyandcompany.com', organization_id: ORGANIZATION_IDS.nyandcompany },
  { hostname: 'officedepot.com', organization_id: ORGANIZATION_IDS.officedepot },
  { hostname: 'oldnavy.com', organization_id: ORGANIZATION_IDS.oldnavy },
  { hostname: 'oldnavy.gap.com', organization_id: ORGANIZATION_IDS.oldnavy },
  { hostname: 'opentable.com', organization_id: ORGANIZATION_IDS.opentable },
  { hostname: 'orbitz.com', organization_id: ORGANIZATION_IDS.orbitz },
  { hostname: 'overstock.com', organization_id: ORGANIZATION_IDS.overstock },
  { hostname: 'payless.com', organization_id: ORGANIZATION_IDS.payless },
  { hostname: 'perfumania.com', organization_id: ORGANIZATION_IDS.perfumania },
  { hostname: 'petcaresupplies.com', organization_id: ORGANIZATION_IDS.petcaresupplies },
  { hostname: 'petco.com', organization_id: ORGANIZATION_IDS.petco },
  { hostname: 'petsmart.com', organization_id: ORGANIZATION_IDS.petsmart },
  { hostname: 'photobox.co.uk', organization_id: ORGANIZATION_IDS.photobox },
  { hostname: 'pier1.com', organization_id: ORGANIZATION_IDS.pieroneimports },
  { hostname: 'poshmark.com', organization_id: ORGANIZATION_IDS.poshmark },
  { hostname: 'priceline.com', organization_id: ORGANIZATION_IDS.priceline },
  { hostname: 'priverevaux.com', organization_id: ORGANIZATION_IDS.priverevaux },
  { hostname: 'proflowers.com', organization_id: ORGANIZATION_IDS.proflowers },
  { hostname: 'puritan.com', organization_id: ORGANIZATION_IDS.puritanspride },
  { hostname: 'quandoo.sg', organization_id: ORGANIZATION_IDS.quandoo },
  { hostname: 'qvc.com', organization_id: ORGANIZATION_IDS.qvc },
  { hostname: 'resy.com', organization_id: ORGANIZATION_IDS.resy },
  { hostname: 'rentalcars.com', organization_id: ORGANIZATION_IDS.rentalcarsdotcom },
  { hostname: 'rover.com', organization_id: ORGANIZATION_IDS.rover },
  { hostname: 'rover.ebay.com', organization_id: ORGANIZATION_IDS.ebay },
  { hostname: 'saksfifthavenue.com', organization_id: ORGANIZATION_IDS.saksfifthavenue },
  { hostname: 'saksoff5th.com', organization_id: ORGANIZATION_IDS.saks },
  { hostname: 'safeway.com', organization_id: ORGANIZATION_IDS.safeway },
  { hostname: 'shop.safeway.com', organization_id: ORGANIZATION_IDS.safeway },
  { hostname: 'samsclub.com', organization_id: ORGANIZATION_IDS.samsclub },
  { hostname: 'samsung.com', organization_id: ORGANIZATION_IDS.samsungdotcom },
  { hostname: 'sears.com', organization_id: ORGANIZATION_IDS.sears },
  { hostname: 'm.sears.com', organization_id: ORGANIZATION_IDS.sears },
  { hostname: 'seatgeek.com', organization_id: ORGANIZATION_IDS.seatgeek },
  { hostname: 'sephora.com', organization_id: ORGANIZATION_IDS.sephora },
  { hostname: 'shoeline.com', organization_id: ORGANIZATION_IDS.shoeline },
  { hostname: 'shoes.com', organization_id: ORGANIZATION_IDS.shoesdotcom },
  { hostname: 'shopdisney.com', organization_id: ORGANIZATION_IDS.shopdisney },
  { hostname: 'shipt.com', organization_id: ORGANIZATION_IDS.shipt },
  { hostname: 'shop.shipt.com', organization_id: ORGANIZATION_IDS.shipt },
  { hostname: 'shopspring.com', organization_id: ORGANIZATION_IDS.spring },
  { hostname: 'sierratradingpost.com', organization_id: ORGANIZATION_IDS.sierratradingpost },
  { hostname: 'siriusxm.com', organization_id: ORGANIZATION_IDS.siriusxm },
  { hostname: 'six02.com', organization_id: ORGANIZATION_IDS.sixzerotwo },
  { hostname: 'skinstore.com', organization_id: ORGANIZATION_IDS.skinstore },
  { hostname: 'society6.com', organization_id: ORGANIZATION_IDS.societysix },
  { hostname: 'soma.com', organization_id: ORGANIZATION_IDS.soma },
  { hostname: 'splendid.com', organization_id: ORGANIZATION_IDS.splendid },
  { hostname: 'staples.com', organization_id: ORGANIZATION_IDS.staples },
  { hostname: 'staples.co.uk', organization_id: ORGANIZATION_IDS.staplesuk },
  { hostname: 'stasher.com', organization_id: ORGANIZATION_IDS.stasher },
  { hostname: 'stevemadden.com', organization_id: ORGANIZATION_IDS.stevemadden },
  { hostname: 'stitchfix.com', organization_id: ORGANIZATION_IDS.stitchfix },
  { hostname: 'strollerhaus.com', organization_id: ORGANIZATION_IDS.strollerhaus },
  { hostname: 'superdry.com', organization_id: ORGANIZATION_IDS.superdry },
  { hostname: 'target.com', organization_id: ORGANIZATION_IDS.target },
  { hostname: 'techarmor.com', organization_id: ORGANIZATION_IDS.techarmor },
  { hostname: 'tedbaker.com', organization_id: ORGANIZATION_IDS.tedbaker },
  { hostname: 'thebodyshop.com', organization_id: ORGANIZATION_IDS.thebodyshop },
  { hostname: 'thelimited.com', organization_id: ORGANIZATION_IDS.thelimited },
  { hostname: 'thredup.com', organization_id: ORGANIZATION_IDS.thredup },
  { hostname: 'thrifty.com', organization_id: ORGANIZATION_IDS.thrifty },
  { hostname: 'thrivemarket.com', organization_id: ORGANIZATION_IDS.thrivemarket },
  { hostname: 'ticketmaster.com', organization_id: ORGANIZATION_IDS.ticketmaster },
  { hostname: 'tillys.com', organization_id: ORGANIZATION_IDS.tillys },
  { hostname: 'tophatter.com', organization_id: ORGANIZATION_IDS.tophatter },
  { hostname: 'usa.tommy.com', organization_id: ORGANIZATION_IDS.tommy },
  { hostname: 'tommy.com', organization_id: ORGANIZATION_IDS.tommy },
  { hostname: 'touchofmodern.com', organization_id: ORGANIZATION_IDS.touchofmodern },
  { hostname: 'travelocity.com', organization_id: ORGANIZATION_IDS.travelocity },
  { hostname: 'tripadvisor.com', organization_id: ORGANIZATION_IDS.tripadvisor },
  { hostname: 'trycaviar.com', organization_id: ORGANIZATION_IDS.caviar },
  { hostname: 'uber.com', organization_id: ORGANIZATION_IDS.uber },
  { hostname: 'm.uber.com', organization_id: ORGANIZATION_IDS.uber },
  { hostname: 'get.uber.com', organization_id: ORGANIZATION_IDS.uberrewards },
  { hostname: 'ulta.com', organization_id: ORGANIZATION_IDS.ulta },
  { hostname: 'underarmour.com', organization_id: ORGANIZATION_IDS.underarmour },
  { hostname: 'viator.com', organization_id: ORGANIZATION_IDS.viator },
  { hostname: 'vitacost.com', organization_id: ORGANIZATION_IDS.vitacost },
  { hostname: 'vitaminworld.com', organization_id: ORGANIZATION_IDS.vitaminworld },
  { hostname: 'vividseats.com', organization_id: ORGANIZATION_IDS.vividseats },
  { hostname: 'vrbo.com', organization_id: ORGANIZATION_IDS.vrbo },
  { hostname: 'walgreens.com', organization_id: ORGANIZATION_IDS.walgreens },
  { hostname: 'thewalkingcompany.com', organization_id: ORGANIZATION_IDS.thewalkingcompany },
  { hostname: 'walmart.com', organization_id: ORGANIZATION_IDS.walmart },
  { hostname: 'warbyparker.com', organization_id: ORGANIZATION_IDS.warbyparker },
  { hostname: 'wine.com', organization_id: ORGANIZATION_IDS.winedotcom },
  { hostname: 'worldmarket.com', organization_id: ORGANIZATION_IDS.costplusworldmarket },
  { hostname: 'yoox.com', organization_id: ORGANIZATION_IDS.yoox },
  { hostname: 'zaful.com', organization_id: ORGANIZATION_IDS.zaful },
  { hostname: 'zulily.com', organization_id: ORGANIZATION_IDS.zulily },
  { hostname: 'buttontestmerchant.com', organization_id: ORGANIZATION_IDS.testmerchant },
];

/**
 * Supported Affiliate Query Ids are the global list of supported affililiate
 * identifiers of Button merchants in an affiliate link's query.  For instance,
 * an affiliate link may look like:
 *
 * https://click.linksynergy.com?id=1234
 *
 * If we know "id" maps to a target merchant and in our space a value of "1234"
 * maps to "org-XXX", we'd declaring the following Supported Affiliate Query Id:
 *
 * {
 *   hostname: 'click.linksynergy.com',
 *   key: 'id',
 *   value: '1234',
 *   organization_id: 'org-XXX',
 *   url: 'http://bloop.net.co.uk'
 * }
 *
 * Supported Affiliate Query Ids have the following schema:
 *
 * hostname [string]: The hostname, including subdomains of the affiliate
 * key [string]: The query param key
 * value [string]: The query param value
 * organization_id [string]: The Button merchant organization id.
 * url [string]: The url to use as a destination on match.
 */
const SUPPORTED_AFFILIATE_QUERY_IDS = [];

/**
 * Supported Affiliate Pathname Ids are the global list of supported affiliate
 * identifiers of Button merchants in an affiliate link's pathname.  For
 * instance, an affiliate link may look like:
 *
 * https://quidco.com/visit/US/123
 *
 * If we know in the "US" namespace, id "123" maps to "org-XXX", we'd declare
 * the following Supported Affiliate Pathname Id:
 *
 * {
 *   hostname: 'quidco.com',
 *   regex: String.raw`\/visit\/(\w{2,})\/\(d{1,})`,
 *   matches: [
 *     { values: ['US', '123'], organization_id: 'org-XXX' }
 *   ]
 * }
 *
 * To be returned in an SDK config, the affiliate hostname must also be declared
 * in `SUPPORTED_AFFILIATES`.
 *
 * Supported Affiliate Pathname Ids have the following schema:
 *
 * hostname [string]: The hostname, including subdomains of the affiliate
 * regex [string]: The regex to match a pathname against
 * redirect [boolean]: Whether or not a match indicates the need to follow a
 *   redirect.
 * getCacheKey [?function]: A function that accepts a matching url and returns
 *   an appropriate hash identifying the uniqueness of the redirect.
 * matches [array<object>]: The match candidates
 * matches[i].values [array<string>]: The match candidate values
 * matches[i].organization_id [string]: The match candidate organization id
 * matches[i].url [string]: The match candidate target url.  As if this was the
 *   eventual redirect location of the link.
 */
const SUPPORTED_AFFILIATE_PATHNAME_IDS = [
  {
    hostname: 'quidco.com',
    regex: String.raw`(?:^|\/)(?:\w{1,}-)?visit\/(\d{1,})(?:$|\/.*)`,
    redirect: false,
    matches: [
      {
        values: ['6078'],
        organization_id: ORGANIZATION_IDS.groupon,
        url: 'https://www.groupon.co.uk',
      },
      {
        values: ['244'],
        organization_id: ORGANIZATION_IDS.hotelsdotcom,
        url: 'https://uk.hotels.com',
      },
      {
        values: ['4439'],
        organization_id: ORGANIZATION_IDS.hungryhouse,
        url: 'https://www.hungryhouse.co.uk',
      },
      {
        values: ['3453'],
        organization_id: ORGANIZATION_IDS.mrandmrssmith,
        url: 'https://www.mrandmrssmith.com',
      },
      {
        values: ['13817'],
        organization_id: ORGANIZATION_IDS.hoteltonight,
        url: 'https://hoteltonight.com',
      },
      {
        values: ['9639'],
        organization_id: ORGANIZATION_IDS.bloomandwild,
        url: 'https://bloomandwild.com',
      },
      {
        values: ['14696'],
        organization_id: ORGANIZATION_IDS.uberrewards,
        url: 'https://get.uber.com',
      },
      {
        values: ['13819'],
        organization_id: ORGANIZATION_IDS.uberrewards,
        url: 'https://get.uber.com',
      },
      {
        values: ['12366'],
        organization_id: ORGANIZATION_IDS.ebay,
        url: 'https://ebay.co.uk',
      },
      {
        values: ['169'],
        organization_id: ORGANIZATION_IDS.asos,
        url: 'https://asos.com',
      },
      {
        values: ['15334'],
        organization_id: ORGANIZATION_IDS.stasher,
        url: 'https://stasher.com',
      },
      {
        values: ['15034'],
        organization_id: ORGANIZATION_IDS.houzz,
        url: 'https://houzz.co.uk',
      },
    ],
  },
  {
    hostname: 'vouchercloud.com',
    regex: String.raw`(?:^|\/)(\w{1,})\/(\w{1,})\/\d{1,}(?:$|\/.*)`,
    redirect: true,
    getCacheKey: null,
    matches: [
      {
        values: ['out', 'offer'],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'groupon.com',
    regex: String.raw`(?:^|\/)(\w{1,})\/(\w{1,})\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(?:$|\/.*)`,
    redirect: true,
    getCacheKey: null,
    matches: [
      {
        values: ['coupons', 'click'],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'prf.hn',
    regex: String.raw`(?:^|\/)click\/camref:[^/]+\/pubref:[^/]+\/(?:creativeref|destination):.+`,
    redirect: true,
    getCacheKey: urlCacheKeyPHG,
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'aos.prf.hn',
    regex: String.raw`(?:^|\/)click\/camref:[^/]+\/pubref:[^/]+\/(?:creativeref|destination):.+`,
    redirect: true,
    getCacheKey: urlCacheKeyPHG,
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'click.linksynergy.com',
    regex: String.raw`^\/?(?:fs-bin\/click|deeplink|link)(?:$|\/.*)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['u1']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'linksynergy.walmart.com',
    regex: String.raw`^\/?(?:fs-bin\/click|deeplink|link)(?:$|\/.*)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['u1']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'anrdoezrs.net',
    regex: String.raw`^\/?click-[0-9]+-[0-9]+(?:-[0-9]+)?(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['sid']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'dpbolvw.net',
    regex: String.raw`^\/?click-[0-9]+-[0-9]+(?:-[0-9]+)?(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['sid']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'jdoqocy.com',
    regex: String.raw`^\/?click-[0-9]+-[0-9]+(?:-[0-9]+)?(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['sid']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'kqzyfj.com',
    regex: String.raw`^\/?click-[0-9]+-[0-9]+(?:-[0-9]+)?(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['sid']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'qksrv.net',
    regex: String.raw`^\/?click-[0-9]+-[0-9]+(?:-[0-9]+)?(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['sid']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'tkqlhce.com',
    regex: String.raw`^\/?click-[0-9]+-[0-9]+(?:-[0-9]+)?(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['sid']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'awin1.com',
    regex: String.raw`^\/?(?:cread|pclick|awclick)\.php(?:$|\/.*)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['clickref']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
  {
    hostname: 'hpn.houzz.com',
    regex: String.raw`^\/?c\/[0-9]+\/[0-9]+\/[0-9]+(?:$|\/)`,
    redirect: true,
    getCacheKey: urlCacheKeyWithQuery(['SubID1']),
    matches: [
      {
        values: [],
        organization_id: null,
        url: null,
      },
    ],
  },
];

/**
 * Supported Affiliates are the global list of affiliates supported for link
 * enhancement.  For instance, an affiliate link may look like:
 *
 * https://click.linksynergy.com?url=https%3A%2F%2Fbloop.com
 *
 * where the affiliate link points at a destination url.  We'd support such a
 * link by declaring the following Supported Affiliate:
 *
 * {
 *   hostname: 'click.linksynergy.com',
 *   display_name: 'Rakuten Linkshare',
 *   query_url_keys: [{ key: 'murl' }]
 * }
 *
 * Supported Affiliates have the following schema:
 *
 * hostname [string]: The hostname of the affiliate
 * display_name [string]: A human-readable name for the affiliate partner
 * query_url_keys [Array<object<string, string>>]: An array of objects where the
 *   "key" element is a string representing the key of the url in the
 *   affiliate's query string.
 */
const SUPPORTED_AFFILIATES = [
  {
    hostname: 'click.linksynergy.com',
    display_name: 'Rakuten Linkshare',
    query_url_keys: [],
  },
  {
    hostname: 'quidco.com',
    display_name: 'Quidco',
    query_url_keys: [],
  },
  {
    hostname: 'prf.hn',
    display_name: 'PHG',
    query_url_keys: [],
  },
  {
    hostname: 'aos.prf.hn',
    display_name: 'PHG',
    query_url_keys: [],
  },
  {
    hostname: 'vouchercloud.com',
    display_name: 'Vouchercloud',
    query_url_keys: [],
  },
  {
    hostname: 'groupon.com',
    display_name: 'Groupon',
    query_url_keys: [],
  },
  {
    hostname: 'linksynergy.walmart.com',
    display_name: 'Rakuten Walmart',
    query_url_keys: [],
  },
  {
    hostname: 'anrdoezrs.net',
    display_name: 'CJ',
    query_url_keys: [],
  },
  {
    hostname: 'dpbolvw.net',
    display_name: 'CJ',
    query_url_keys: [],
  },
  {
    hostname: 'jdoqocy.com',
    display_name: 'CJ',
    query_url_keys: [],
  },
  {
    hostname: 'kqzyfj.com',
    display_name: 'CJ',
    query_url_keys: [],
  },
  {
    hostname: 'qksrv.net',
    display_name: 'CJ',
    query_url_keys: [],
  },
  {
    hostname: 'tkqlhce.com',
    display_name: 'CJ',
    query_url_keys: [],
  },
  {
    hostname: 'shareasale.com',
    display_name: 'ShareASale',
    query_url_keys: [{ key: 'urllink' }],
  },
  {
    hostname: 'awin1.com',
    display_name: 'Awin',
    query_url_keys: [],
  },
  {
    hostname: 'hpn.houzz.com',
    display_name: 'Impact Radius',
    query_url_keys: [],
  },
];

module.exports = {
  ORGANIZATION_IDS,
  SUPPORTED_MERCHANTS,
  SUPPORTED_AFFILIATE_QUERY_IDS,
  SUPPORTED_AFFILIATE_PATHNAME_IDS,
  SUPPORTED_AFFILIATES,
};
